name: pallery
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.8

dependencies:
  animated_text_kit: ^4.2.2
  bloc: ^8.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.2.17
  go_router: ^6.0.0
  google_fonts: ^3.0.1
  intl: ^0.17.0
  rive: ^0.10.0

dev_dependencies:
  bloc_test: ^9.1.0
  build_runner: ^2.3.0
  flutter_gen_runner: ^5.1.0+1
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/animation/
