name: pallery
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.8

dependencies:
  animated_text_kit: ^4.2.2
  bloc: ^8.1.0
  carousel_slider: ^4.2.1
  copy_with_extension: ^5.0.0
  envied: ^0.3.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.0.4
  font_awesome_flutter: ^10.3.0
  go_router: ^6.0.0
  google_fonts: ^3.0.1
  intl: ^0.17.0
  isar: ^3.0.5
  isar_flutter_libs: ^3.0.5
  logger: ^1.2.2
  rive: ^0.10.0
  sentry_flutter: ^6.18.2
  settings_ui: ^2.0.2

dev_dependencies:
  bloc_test: ^9.1.0
  build_runner: ^2.3.0
  copy_with_extension_gen: ^5.0.0
  envied_generator: 0.3.0
  flutter_gen_runner: ^5.1.0+1
  flutter_test:
    sdk: flutter
  isar_generator: ^3.0.5
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0

dependency_overrides:
  test_api: 0.4.16

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/animation/
